# Name of your application. Used to uniquely configure containers.
service: test_deploy

# Name of the container image.
image: erkhovalexander/test_site

# Deploy to these servers.
servers:
  web:
    - 82.202.140.99
  ports:
    - "80:80"

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: erkhovalexander

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

ssh:
  user: eroha

