name: test_deploy

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: secrets:
        run: mkdir .kamal && echo "KAMAL_REGISTRY_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" > .kamal/secrets
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 82.202.140.99  >> ~/.ssh/known_hosts
      - name: kamal
        run: kamal deploy
